"""Pull-request title and body, built from the plan and the patch.

F6-02 requires the pull request to describe the tools, the changed files and the
validation results. Composed deterministically rather than accepted from a
caller, so the description always matches what is actually being proposed — and
so it can be scanned before it leaves, which §4.4 requires of outbound content.
"""

from __future__ import annotations

from mcpforge.models.patch import GeneratedPatch
from mcpforge.models.toolplan import ToolPlan


def default_title(plan: ToolPlan) -> str:
    count = len(plan.tools)
    return f"Add {count} WebMCP tool{'' if count == 1 else 's'} (generated by MCPForge)"


def describe_patch(
    plan: ToolPlan,
    patch: GeneratedPatch,
    *,
    branch: str,
    base_commit: str,
    validation: str | None = None,
) -> str:
    """The pull-request body.

    Written for the developer reviewing it, not for a changelog: it says what
    each tool does, which of their functions it calls, and which ones stop for a
    human. Nothing here is a claim about work that did not happen — the
    validation section is omitted when there is no validation report.
    """
    gated = [t for t in plan.tools if t.approval_required]

    lines = [
        "This pull request was generated by MCPForge and reviewed by a human before it was opened.",
        "",
        "## Tools",
        "",
        "| Tool | Risk | Calls your function | Human approval |",
        "| --- | --- | --- | --- |",
    ]
    for tool in plan.tools:
        approval = "Required" if tool.approval_required else "Not required"
        lines.append(
            f"| `{tool.name}` | {tool.risk.value} | `{tool.maps_to_function}()` | {approval} |"
        )

    lines += ["", "### What each tool does", ""]
    for tool in plan.tools:
        lines.append(f"- **`{tool.name}`** — {tool.description}")

    lines += [
        "",
        "Every handler calls the function named above. No business logic is "
        "duplicated, so changing that function changes the tool.",
        "",
        "## Files",
        "",
        f"{len(patch.files)} file(s) added, +{patch.total_added}/-{patch.total_removed}.",
        "",
    ]
    for change in patch.files:
        lines.append(f"- `{change.path}` — {change.rationale}")

    if gated:
        lines += [
            "",
            "## What stops for you",
            "",
            f"{len(gated)} tool(s) change state and do not act on their own. They record "
            "an approval request and return its id, so an AI agent cannot complete them "
            "without a person deciding:",
            "",
        ]
        lines += [f"- `{t.name}` ({t.risk.value})" for t in gated]
        lines += [
            "",
            "They post to `/api/webmcp/approvals`, which is yours to implement. Until you "
            "do, those tools refuse rather than act.",
        ]

    if validation:
        lines += ["", "## Validation", "", validation]

    lines += [
        "",
        "---",
        "",
        f"Branch `{branch}` from `{base_commit[:12]}`. Merge it as you normally would.",
    ]
    return "\n".join(lines)
