"""Next.js WebMCP code generation — ticket F5-02, 02_ARCHITECTURE.md §10.

**The code is emitted deterministically from the validated tool contract, not
written by a model.** The model's judgement was already spent deciding *which*
tools to build and *what* they map to; the remaining step is mechanical, and a
template cannot hallucinate an import, invent a function, or quietly reimplement
business logic. It also means the output is reviewable as a diff of known shape.

What is generated, per `02_ARCHITECTURE.md` §10:

    src/webmcp/
    ├── types.ts       shared result shape
    ├── adapter.ts     feature detection, real + labelled mock
    ├── register.ts    lifecycle, one registration per tool
    └── tools/*.ts     one file per tool, each importing the existing function

Every handler calls the developer's own function. Nothing is reimplemented.
"""

from __future__ import annotations

from mcpforge.models.patch import ChangeKind, FileChange, GeneratedPatch
from mcpforge.models.webmcp import CallStyle, WebMCPTool, WebMCPToolset

WEBMCP_DIR = "src/webmcp"

GENERATED_HEADER = """\
// Generated by MCPForge. Reviewed and approved before it reached this branch.
//
// Handlers call your existing functions — they do not reimplement any logic.
// Edit the underlying function, not this file, unless you mean to change the
// tool contract itself.
"""

TYPES_TS = (
    GENERATED_HEADER
    + """
/** What every MCPForge tool returns to a calling agent. */
export type ToolResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string; code: ToolErrorCode }
  | {
      ok: false;
      awaitingApproval: true;
      approvalId: string;
      error: string;
      code: "approval_required";
    };

export type ToolErrorCode =
  | "invalid_input"
  | "not_found"
  | "forbidden"
  | "approval_required"
  | "failed";

export function ok<T>(data: T): ToolResult<T> {
  return { ok: true, data };
}

export function failed(error: string, code: ToolErrorCode = "failed"): ToolResult<never> {
  return { ok: false, error, code };
}

/**
 * A tool that changes state returns this instead of acting.
 *
 * The approval is a record on the server. An agent cannot approve on the
 * developer's behalf, and there is no argument that skips this.
 */
export function awaitingApproval(approvalId: string, what: string): ToolResult<never> {
  return {
    ok: false,
    awaitingApproval: true,
    approvalId,
    code: "approval_required",
    error: `${what} needs human approval. Approval ${approvalId} is pending.`,
  };
}
"""
)

ADAPTER_TS = (
    GENERATED_HEADER
    + """
/**
 * WebMCP adapter.
 *
 * The W3C Web Machine Learning CG draft puts the API on `document.modelContext`.
 * Some early implementations expose `navigator.modelContext`, so both are
 * probed and the one found is reported. The draft has no `unregisterTool`:
 * teardown is the AbortSignal passed to registerTool.
 *
 * This file is the only place that knows the API shape, so spec drift is one
 * file's problem.
 */

export interface ModelContextTool {
  name: string;
  title?: string;
  description: string;
  inputSchema?: Record<string, unknown>;
  execute: (input: Record<string, unknown>) => Promise<unknown>;
}

export interface ModelContextLike {
  registerTool(tool: ModelContextTool, options?: { signal?: AbortSignal }): Promise<void>;
}

export type AdapterSurface = "document" | "navigator" | "unsupported";

export interface WebMCPAdapter {
  readonly surface: AdapterSurface;
  readonly supported: boolean;
  register(tool: ModelContextTool, signal: AbortSignal): Promise<void>;
}

function findModelContext(): { context: ModelContextLike; surface: AdapterSurface } | null {
  if (typeof document !== "undefined") {
    const candidate = (document as unknown as { modelContext?: ModelContextLike }).modelContext;
    if (candidate?.registerTool) return { context: candidate, surface: "document" };
  }
  if (typeof navigator !== "undefined") {
    const candidate = (navigator as unknown as { modelContext?: ModelContextLike }).modelContext;
    if (candidate?.registerTool) return { context: candidate, surface: "navigator" };
  }
  return null;
}

/** Real browser WebMCP, or an honest report that it is unavailable. */
export function createAdapter(): WebMCPAdapter {
  const found = findModelContext();

  if (!found) {
    return {
      surface: "unsupported",
      supported: false,
      async register() {
        // Not an error: most browsers do not implement WebMCP yet. The site
        // keeps working for humans, which is the point.
      },
    };
  }

  return {
    surface: found.surface,
    supported: true,
    async register(tool, signal) {
      await found.context.registerTool(tool, { signal });
    },
  };
}
"""
)


def _tool_file(tool: WebMCPTool) -> str:
    """One tool. Imports the developer's function and calls it."""
    interface = tool.input_interface()
    required = [p for p in tool.inputs if p.required]
    alias = tool.import_alias
    call_args = _call_arguments(tool)
    awaited = "await " if tool.source.is_async else ""

    checks = "\n".join(
        f"  if (input.{p.name} === undefined || input.{p.name} === null) {{\n"
        f'    return failed("{p.name} is required", "invalid_input");\n'
        f"  }}"
        for p in required
    )

    if tool.approval_required:
        body = f'''  // {tool.risk.value}: this changes state, so it stops here.
  //
  // MCPForge requests approval and returns the pending id. The developer
  // approves in the application; an agent cannot approve on their behalf.
  const approvalId = await requestApproval({{
    tool: "{tool.name}",
    risk: "{tool.risk.value}",
    input: input as unknown as Record<string, unknown>,
  }});
  return awaitingApproval(approvalId, "{tool.title}");'''
    else:
        body = f"""  try {{
    const result = {awaited}{alias}({call_args});
    return ok(result);
  }} catch (error) {{
    // Structured, never a raw exception: the message reaches an AI agent.
    return failed(error instanceof Error ? error.message : "The call failed");
  }}"""

    approval_import = (
        '\nimport { requestApproval } from "@/webmcp/approvals";' if tool.approval_required else ""
    )
    result_helpers = "awaitingApproval, failed" if tool.approval_required else "failed, ok"

    return f'''{GENERATED_HEADER}
import {{ {tool.source.symbol} as {alias} }} from "{tool.source.module}";
import {{ {result_helpers}, type ToolResult }} from "@/webmcp/types";{approval_import}

export interface {tool.type_name}Input {{
{interface}
}}

export const {tool.handler_name}Schema = {{
  name: "{tool.name}",
  title: "{tool.title}",
  description: "{tool.description}",
  inputSchema: {_schema_literal(tool)},
}} as const;

/**
 * {tool.description}
 *
 * Risk: {tool.risk.value}{" — human approval required" if tool.approval_required else ""}
 * Calls: {tool.source.symbol}() from {tool.source.module}
 */
export async function {tool.handler_name}(
  input: {tool.type_name}Input,
): Promise<ToolResult<unknown>> {{
{checks + chr(10) if checks else ""}{body}
}}
'''


def _call_arguments(tool: WebMCPTool) -> str:
    """Build the call the way the target function is actually declared.

    Ordered by the function's own parameter list, not by the tool's input order,
    so a reordered schema cannot silently swap two arguments of the same type.
    """
    names = tool.source.parameters or [p.name for p in tool.inputs]
    if tool.source.call_style is CallStyle.OBJECT:
        fields = ", ".join(f"{name}: input.{name}" for name in names)
        return "{ " + fields + " }"
    return ", ".join(f"input.{name}" for name in names)


def _schema_literal(tool: WebMCPTool) -> str:
    import json

    return json.dumps(tool.input_schema(), indent=2).replace("\n", "\n  ")


def _register_file(toolset: WebMCPToolset) -> str:
    imports = "\n".join(
        f"import {{ {t.handler_name}, {t.handler_name}Schema }} "
        f'from "@/webmcp/tools/{t.handler_name}";'
        for t in toolset.tools
    )
    registrations = "\n".join(
        f"""    adapter.register(
      {{
        ...{t.handler_name}Schema,
        execute: (input) => {t.handler_name}(input as never),
      }},
      controller.signal,
    ),"""
        for t in toolset.tools
    )

    return f"""{GENERATED_HEADER}
import {{ createAdapter }} from "@/webmcp/adapter";
{imports}

/**
 * Registers every MCPForge tool and returns a teardown function.
 *
 * Call it once where your app mounts. Registration is torn down by aborting the
 * signal, which is how the WebMCP draft unregisters tools — there is no
 * unregisterTool.
 *
 * In React:
 *
 *     useEffect(() => registerWebMCPTools(), []);
 */
export function registerWebMCPTools(): () => void {{
  const adapter = createAdapter();
  const controller = new AbortController();

  if (!adapter.supported) {{
    // This browser has no WebMCP. The site works normally for humans.
    return () => controller.abort();
  }}

  void Promise.all([
{registrations}
  ]);

  return () => controller.abort();
}}

export {{ createAdapter }};
"""


APPROVALS_TS = (
    GENERATED_HEADER
    + """
/**
 * Approval requests for state-changing tools.
 *
 * A tool that changes state does not act. It records a pending approval and
 * returns its id, and the developer decides in the application.
 *
 * Point this at your own approval surface. The default posts to an endpoint you
 * implement; what matters is that a human decides, and that the decision is
 * recorded somewhere your server trusts — not asserted by the caller.
 */

export interface ApprovalRequest {
  tool: string;
  risk: string;
  input: Record<string, unknown>;
}

export async function requestApproval(request: ApprovalRequest): Promise<string> {
  const response = await fetch("/api/webmcp/approvals", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });

  if (!response.ok) {
    throw new Error(`Could not request approval: ${response.status}`);
  }

  const body = (await response.json()) as { approvalId?: string };
  if (!body.approvalId) {
    throw new Error("The approval endpoint returned no approval id");
  }
  return body.approvalId;
}
"""
)


def generate_patch(toolset: WebMCPToolset, *, base_commit: str | None = None) -> GeneratedPatch:
    """Emit the integration for a validated toolset."""
    files: list[FileChange] = [
        FileChange(
            path=f"{WEBMCP_DIR}/types.ts",
            kind=ChangeKind.ADD,
            contents=TYPES_TS,
            rationale="Shared result shape so every tool answers an agent the same way.",
        ),
        FileChange(
            path=f"{WEBMCP_DIR}/adapter.ts",
            kind=ChangeKind.ADD,
            contents=ADAPTER_TS,
            rationale=(
                "Feature-detects the browser WebMCP API and degrades cleanly where it is absent."
            ),
        ),
    ]

    if toolset.requires_approval:
        files.append(
            FileChange(
                path=f"{WEBMCP_DIR}/approvals.ts",
                kind=ChangeKind.ADD,
                contents=APPROVALS_TS,
                rationale=(
                    "State-changing tools pause here for a human decision instead of acting."
                ),
            )
        )

    for tool in toolset.tools:
        files.append(
            FileChange(
                path=f"{WEBMCP_DIR}/tools/{tool.handler_name}.ts",
                kind=ChangeKind.ADD,
                contents=_tool_file(tool),
                rationale=(
                    f"Exposes {tool.title.lower()} to AI agents by calling your existing "
                    f"{tool.source.symbol}()."
                ),
                affected_tool=tool.name,
            )
        )

    files.append(
        FileChange(
            path=f"{WEBMCP_DIR}/register.ts",
            kind=ChangeKind.ADD,
            contents=_register_file(toolset),
            rationale="Registers every tool on mount and tears them down on unmount.",
        )
    )

    gated = len(toolset.requires_approval)
    return GeneratedPatch(
        files=files,
        base_commit=base_commit,
        summary=(
            f"Adds {len(toolset.tools)} WebMCP tool(s) across {len(files)} files. "
            f"{gated} require human approval and pause rather than acting. "
            "Every handler calls an existing function; no business logic is duplicated."
        ),
    )
